# Generated by Django 4.2 on 2024-04-13 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150, unique=True, verbose_name='email')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('father_name', models.CharField(max_length=150, verbose_name='отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='содержимое')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time_mail', models.DateTimeField(auto_now=True, verbose_name='дата и время последней попытки')),
                ('status', models.CharField(max_length=50, verbose_name='статус попытки')),
                ('response', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='рассылка', max_length=100, verbose_name='Название рассылки')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='дата начала рассылки')),
                ('date_next', models.DateTimeField(default=django.utils.timezone.now, verbose_name='следующая дата рассылки')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания рассылки')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='время рассылки')),
                ('period', models.CharField(choices=[('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], default='раз в день', max_length=50, verbose_name='периодичность рассылки')),
                ('status', models.CharField(choices=[('создана', 'создана'), ('завершена', 'завершена'), ('запущена', 'запущена')], default='создана', max_length=50, verbose_name='статус рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активация рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'permissions': [('set_is_active', 'Активация рассылки')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='тема письма')),
                ('body', models.TextField(blank=True, null=True, verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
